{% set version = "2018.4" %}

package:
  name: pytzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytzdata/pytzdata-{{ version }}.tar.gz
  sha256: 33456d0c1a9f6dc103749b3a00099a8b5bfea9d1c292526ec3dffe5c7df1f752

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pytzdata

about:
  home: https://github.com/sdispater/pytzdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Official timezone database for Python'

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
