{% set version = "2017.3" %}

package:
  name: pytzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytzdata/pytzdata-{{ version }}.tar.gz
  sha256: 1bae4bb50b6be6e9120d73f7366139c0e33d40d230bbace7138490017308ab7b

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pytzdata

about:
  home: https://github.com/sdispater/pytzdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Official timezone database for Python'

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
