{% set version = "2018.9" %}

package:
  name: pytzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytzdata/pytzdata-{{ version }}.tar.gz
  sha256: dddaaf4f1717820a6fdcac94057e03c1a15b3829a44d9eaf19988917977db408

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pytzdata

about:
  home: https://github.com/sdispater/pytzdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Official timezone database for Python'

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
