{% set version = "2018.5" %}

package:
  name: pytzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytzdata/pytzdata-{{ version }}.tar.gz
  sha256: e4ef42e82b0b493c5849eed98b5ab49d6767caf982127e9a33167f1153b36cc5

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pytzdata

about:
  home: https://github.com/sdispater/pytzdata
  license: MIT
  license_family: MIT
  summary: 'Official timezone database for Python'

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
