{% set version = "2018.3" %}

package:
  name: pytzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytzdata/pytzdata-{{ version }}.tar.gz
  sha256: 4e2cceb54335cd6c28caea46b15cd592e2aec5e8b05b0241cbccfb1b23c02ae7

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pytzdata

about:
  home: https://github.com/sdispater/pytzdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Official timezone database for Python'

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
