travis:
  secure:
    BINSTAR_TOKEN: OJBzAgsS1m6rmwlRa/fLt975Jf2I0LmFkE39yNGAwf6sBRmtjEALyBwIosyJtrQ1kKgvSQxmJGXM1OSHyvSHjgu092emwU6WOv8y88G7jWXBcQ37PzSUTuI6ZD6k0ACfNTmEJ8xh8EAO0o30fasVSxgbtRn2pRK4WPvKFLHFe2iAdzlm1ZyeYLpj1qxI4AzkXN/S4oS7t7ai5Ouknm79CooF+9aNEd05QeokEoiq+m1bPWZobBbjVqcioSnJpG1X45E8I6Q8It3mdbWyFV7Jh/Ok/88cBlTS+sXpKIyHKqeVo3b8KtzoOrcCRHZ1sEV5GFnIfZOC4/HhxYG6ou/iweKmG4NMb7ehN1I+tPm6KIHnolWMhKCpd004DbTrgUebP3dA5us3Koj+di3xqwZlDoPk6ySvuZhPlpp4FcPfkjZnxxqK/EBj2ndp7+m+0UuIKaHzauHRx5SqOA5DZndxcDUPYeso00+PBmSr11LKlNAyDn3oydjTyIPllLgVD29lPo/PB5lYl27NAdp6kFuJ0U8kNCdtG4bo6gW87s690+SOfUXsHCrWakJVZOlOItldfuKMTToNrNVYvj0/tnuOTZBfS272EZV94EUb88K0zCnZhOwaKC6J1U2oj41y16lQrh1G6msCa4r8HDJGnQEdmgsdSFW4IOezIbLrzshLIGY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
