travis:
  secure:
    BINSTAR_TOKEN: mXFoOxcgBYl+DugcoYm6n6pwC1JCXfjeGNZE6+utjJStTLqNoSHGkyIm5tnLxAq03WKSafeUVzWhKV5QRDTUvwbZxMs2pTtqKu5DojohzYMmRhgxjIyfhnShxJZtOhvHVSDCGXf5UMVIYTN49XNRemKpD5NWdUoVMF1PQTDjm+SX9tfllXy7rcKvI31LMT9D7eOId4hPdlU3qMJJ06IBh/DjR5lLQdYWw/+iLdInbwfhgy/LhijQKvxpwQp3sXbtlByu84Y2+eew32AnNc6FB1eUAttFgiSxPpafuYjRDCvCEn0yPdXDoTZNLJFLNQ6D7ztqTaVydZHe5T4gB+DmCnfwRxzOng+dCRQSqHtMULB0pnlFieVRhkLwc4aIhc0F9co8+tZ9PXu2x+EUVFq0lmkcqKJrXn4vut2V+ty00NOR4788xIiBs+FRN/2HchRzl2ydBc+4dKX8CaTrMUSo97c1ODBC1wDlduOyhYhq4eD4rvhTbmvFfkj7lCRopQEVYuhSoyL2Qceq28X7e9mbFK5eYfRu/t8Vqfb44Tk70n36Cf1Io9BrN+lsOriT9HyszXT73RHCpRAAadrA/ZDimAJl8W/Xi3iCrm6XEKg6UkKTi1D7uyustoqjHkYmQAciGELRf3MrQ+zOy10gAO/93uALdiox29ucphvn2clri9U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
