travis:
  secure:
    BINSTAR_TOKEN: oc9MNEXpvVtZeFLwmnZTtv2P4mcxOb9e5cboSFWCpHLQdJpzQ0yijW5YRS6E81QMyDkfmCO+pJ75/hOq1QHlrUTF0Q2BJy1+38G5ANOfbg8VO88Sdwo3FmTgVEFZ2qEimwhSvn/qYhVUW6FiICMqRleZjamHmbp/vFcKikPFMS0NhlcBRKwVuiazDgsvkDuqcIdJpKzvPS1wcxWNDrLk/Kx8j9pgyUPZbfg/t5n0GBVCZisrn4rIArp1LpjFOzDlvz5uAoRevTG8USrCeuBBTX0EeZxN/lnMCKQpd19LkBG9UmpViOQweHKay6TuCHcN4DitJLdkEDUgTiEG0G1fCJVm7IL5pXczprEgELS/+C33CPuN29V9pNvuJ4flZ1Q/8bGZfGO0ee74YgyozNLusMW0grcm2EoGshSuXQZaRX2awK0vt8GbpD2cJTqvvqBRXH3MWGj1L11UzsXhqa6xzWZGfYdZfe8DS9PnolddyI41ScZjUIifoP+Xet+FRSKjt62vt3wVTNa4nMifKB40ZXgISHajowRgSGh6rIgDtE8evYG5DoYQsIdFBQ5Z/IuGWZVrdPVZorZ48p6mHpgmN+WVJoHb+qPqQNhRCcPk8eLLpDX7RXyi+ViCRPjcAgp4DH07U9bNG0ALg3NjF2g1Yn1+2K2orcY2IUEXzihUQ7c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
